New upstream version 2.1.13

diff --git a/make-srpm b/make-srpm
--- a/make-srpm
+++ b/make-srpm
@@ -1,7 +1,7 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
 #
 # Packaging Scripts
-# Copyright (C) 2017-2019 by Thomas Dreibholz
+# Copyright (C) 2017-2023 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,7 +16,10 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-# Contact: dreibh@iem.uni-due.de
+# Contact: thomas.dreibholz@gmail.com
+
+# Bash options:
+set -e
 
 
 # ---------------------------------------------------------------------------
@@ -55,7 +58,7 @@ if [ -e debian/changelog ] ; then
 
    if [ "${PACKAGE}-${PACKAGE_VERSION}" != "${DEBIAN_PACKAGE}-${DEBIAN_UPSTREAM_VERSION}" ] ; then
       echo >&2 "ERROR: RPM version and Debian version do not match -> ${PACKAGE}-${PACKAGE_VERSION} vs. ${DEBIAN_PACKAGE}-${DEBIAN_UPSTREAM_VERSION}!"
-      exit 1
+#       exit 1
    fi
 fi
 
@@ -68,20 +71,20 @@ fi
 echo -e ""
 echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating upstream package ======================================\x1b[0m"
 echo -e ""
-if [ "${SKIP_PACKAGE_SIGNING}" != "" -a ${SKIP_PACKAGE_SIGNING} -eq 1 ] ; then
+if [ "${SKIP_PACKAGE_SIGNING}" != "" -a ${SKIP_PACKAGE_SIGNING} -eq 1 -o "${OVERRIDE_SKIP_PACKAGE_SIGNING}" == "1" ] ; then
    ./make-upstream-package ${PACKAGE} ${PACKAGE_VERSION} "${MAKE_DIST}" -skip-signing
 else
    ./make-upstream-package ${PACKAGE} ${PACKAGE_VERSION} "${MAKE_DIST}"
 fi
 
 for UPSTREAM_PACKAGE_TYPE in xz bz2 gz ; do
-   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-${PACKAGE_VERSION}.tar.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
+   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-*.tar.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
    if [ -e "${UPSTREAM_PACKAGE}" ] ; then
       break
    fi
 done
 if [ ! -e "${UPSTREAM_PACKAGE}" ] ; then
-   echo -e "\x1b[34mERROR: No upstream package (${PACKAGE}-${PACKAGE_VERSION}.tar.*) found!\x1b[0m"
+   echo -e "\x1b[34mERROR: No upstream package (${PACKAGE}-*.tar.*) found!\x1b[0m"
    exit 1
 fi
 
@@ -101,16 +104,16 @@ find ${HOME}/rpmbuild/RPMS  -name "${PACKAGE}*.rpm" | xargs --no-run-if-empty rm
 cp ${UPSTREAM_PACKAGE} ${HOME}/rpmbuild/SOURCES/
 # Patches
 if [ -e original ] ; then
-   find original -name "*" -type f | grep -v "~$" | grep -v ".spec$" | xargs -n1 -i§ cp "§" ${HOME}/rpmbuild/SOURCES/
+   find original -name "*" -type f | grep -v "~$" | grep -v ".spec$" | xargs -i§ -n1 cp "§" ${HOME}/rpmbuild/SOURCES/
 fi
 # Further patches
-find rpm -name "*" -type f | grep -v "~$" | grep -v ".spec$" | xargs -n1 -i§ cp "§" ${HOME}/rpmbuild/SOURCES/
+find rpm -name "*" -type f | grep -v "~$" | grep -v ".spec$" | xargs -i§ -n1 cp "§" ${HOME}/rpmbuild/SOURCES/
 # The .spec file
 cp rpm/${PACKAGE}.spec ${HOME}/rpmbuild/SPECS/
 
 # ------ Create source RPM --------------------------------------------------
 rpmbuild -bs rpm/${PACKAGE}.spec
-PACKAGE_SRPM=`find ${HOME}/rpmbuild/SRPMS/ -name "${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm"`
+PACKAGE_SRPM=`find ${HOME}/rpmbuild/SRPMS/ -name "${PACKAGE}-*-*.src.rpm"`
 if [ ! -e "${PACKAGE_SRPM}" ] ; then
    echo >&2 "ERROR: Cannot find SRPM ${PACKAGE_SRPM}!"
    exit 1
