New upstream version 3.0.5

diff --git a/freebsd/fractgen/test-packaging b/freebsd/fractgen/test-packaging
--- a/freebsd/fractgen/test-packaging
+++ b/freebsd/fractgen/test-packaging
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # Free Packaging Test Script
-# Copyright (C) 2010-2021 by Thomas Dreibholz
+# Copyright (C) 2010-2024 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,22 +18,22 @@
 #
 # Contact: thomas.dreibholz@gmail.com
 
-PACKAGE=`cat Makefile | grep PORTNAME= | sed -e "s/^PORTNAME=//g" | tr -d " \t"`
-UPSTREAM_VERSION=`cat Makefile | grep PORTVERSION= | sed -e "s/^PORTVERSION=//g" | tr -d " \t"`
-PORTREVISION=`cat Makefile | grep PORTREVISION= | sed -e "s/^PORTREVISION=//g" | tr -d " \t"`
-CATEGORY=`cat Makefile | grep CATEGORIES= | sed -e "s/^CATEGORIES=//g" | tr -d " \t"`
+PACKAGE=`cat Makefile | grep "^PORTNAME=" | sed -e "s/^PORTNAME=//g" | tr -d " \t"`
+UPSTREAM_VERSION=`cat Makefile | grep "^DISTVERSION=" | sed -e "s/^DISTVERSION=//g" | tr -d " \t"`
+PORTREVISION=`cat Makefile | grep "^PORTREVISION=" | sed -e "s/^PORTREVISION=//g" | tr -d " \t"`
+CATEGORY=`cat Makefile | grep "^CATEGORIES=" | sed -e "s/^CATEGORIES=//g" | tr -d " \t"`
 
 PACKAGE_VERSION="${UPSTREAM_VERSION}"
-if [ "$PORTREVISION" != "" ] ; then
+if [ "${PORTREVISION}" != "" ] ; then
    PACKAGE_VERSION="${UPSTREAM_VERSION}_${PORTREVISION}"
 fi
 
 
 echo "######################################################################"
-echo "PACKAGE:          $PACKAGE"
-echo "UPSTREAM_VERSION: $UPSTREAM_VERSION"
-echo "PACKAGE_VERSION:  $PACKAGE_VERSION"
-echo "CATEGORY:         $CATEGORY"
+echo "PACKAGE:          ${PACKAGE}"
+echo "UPSTREAM_VERSION: ${UPSTREAM_VERSION}"
+echo "PACKAGE_VERSION:  ${PACKAGE_VERSION}"
+echo "CATEGORY:         ${CATEGORY}"
 echo "######################################################################"
 
 
@@ -41,7 +41,9 @@ if [ -e work ] ; then
    rm -rf work
 fi
 rm -f ${PACKAGE}-${PACKAGE_VERSION}.txz
-find /usr/ports/packages -name "${PACKAGE}*.txz" | xargs rm -f
+if [ -d work/pkg ] ; then
+   find work/pkg -name "${PACKAGE}*.txz" | xargs rm -f
+fi
 
 
 echo "1. ###### make deinstall ##############################################" && \
@@ -53,22 +55,19 @@ make package && \
 echo "4. ###### make deinstall ##############################################" && \
 make deinstall && \
 echo "5. ###### pkg add #####################################################" && \
-if [ -e work/pkg/${PACKAGE}-${PACKAGE_VERSION}.txz ] ; then
-   mkdir /usr/ports/packages /usr/ports/packages/All
-   cp work/pkg/${PACKAGE}-${PACKAGE_VERSION}.txz /usr/ports/packages/All
-else
-   echo >&2 "ERROR: Cannot find work/pkg/${PACKAGE}-${PACKAGE_VERSION}.txz!"
+if [ ! -e "work/pkg/${PACKAGE}-${PACKAGE_VERSION}.pkg" ] ; then
+   echo >&2 "ERROR: Package work/pkg/${PACKAGE}-${PACKAGE_VERSION}.pkg not found!"
    exit 1
-fi
-pkg add /usr/ports/packages/All/${PACKAGE}-${PACKAGE_VERSION}.txz && \
+fi && \
+pkg add work/pkg/${PACKAGE}-${PACKAGE_VERSION}.pkg && \
 echo "6. ###### make deinstall ##############################################" && \
 make deinstall && \
 echo "7. ###### make reinstall ##############################################" && \
 make reinstall && \
 echo "8. ###### make package ################################################" && \
 make package && \
-echo "9. ###### tar tzvf *.txz ##############################################" && \
-tar tzvf /usr/ports/packages/All/${PACKAGE}-${PACKAGE_VERSION}.txz && \
+echo "9. ###### tar tzvf *.pkg ##############################################" && \
+tar tzvf work/pkg/${PACKAGE}-${PACKAGE_VERSION}.pkg && \
 echo "Running portlint ..." && \
 portlint && \
 echo "====== Successfully completed! ======"
